trigger:
- master
- public/0.8.x

variables:
- template: settings/common.yml

stages:
- stage: Windows
  dependsOn: []
  pool:
    vmImage: 'windows-2019'
  # uncomment after switching to UE4.25
  variables:
    - template: settings/ue425undefs.yml
  jobs:
  - job:
    workspace:
      clean: all
    steps:
    - checkout: self
      clean: true
      submodules: true
    - template: templates/common.yml

    - script: '"$(UnrealEngine)\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun -project=$(UXTSourceDir)\UXToolsGame\UXToolsGame.uproject -clean -cook -allmaps -build -stage -targetplatform=Android -cookflavor=Multi -clientconfig=Development -serverconfig=Development'
      displayName: 'Build Android Development'
